# Generated by Django 3.1.6 on 2021-02-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_image_is_main'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_stock',
            field=models.ManyToManyField(through='order.OrderProductStock', to='product.ProductStock'),
        ),
    ]
